#! /bin/bash

install_horizon () {

 #. /root/bomsi/lib/bomsi_vars

  apt-get -y install openstack-dashboard

  TMPF="/etc/openstack-dashboard/local_settings.py"
  sed -i "s/.*OPENSTACK_HOST =.*/OPENSTACK_HOST = \"controller\"/" $TMPF
  sed -i "s/^ALLOWED_HOSTS =.*/ALLOWED_HOSTS = ['*', ]/" $TMPF

  echo "SESSION_ENGINE = 'django.contrib.sessions.backends.cache'" >> $TMPF
  sed -i "s/'LOCATION': '127.0.0.1:11211'/'LOCATION': 'controller:11211'/" $TMPF

  sed -i 's/^OPENSTACK_KEYSTONE_URL =.*/OPENSTACK_KEYSTONE_URL = "http://%s:5000/v3" % OPENSTACK_HOST/' $TMPF

  sed -i 's/.*OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = .*/OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True/' $TMPF

  echo 'OPENSTACK_API_VERSIONS = {' >> $TMPF
  echo '  "identity": 3,' >> $TMPF
  echo '  "image": 2,' >> $TMPF
  echo '  "volume": 2,' >> $TMPF
  echo '}' >> $TMPF

  sed -i 's/.*OPENSTACK_KEYSTONE_DEFAULT_DOMAIN.*/OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = "default"/' $TMPF

  sed -i 's/.*OPENSTACK_KEYSTONE_DEFAULT_ROLE.*/OPENSTACK_KEYSTONE_DEFAULT_ROLE = "user"/' $TMPF

  #sed -i 's/.*TIME_ZONE.*/TIME_ZONE = "UTC"/' $TMPF


  #sed -i "s/OPENSTACK_KEYSTONE_DEFAULT_ROLE =.*/OPENSTACK_KEYSTONE_DEFAULT_ROLE = \"user\"/" $TMPF
  
  # Restart apache
  service apache2 reload

}


