#! /bin/bash

install_neutron_controller_self-serv () {
 . /root/bomsi/lib/bomsi_vars
 . ~/admin-openrc.sh

  # Install exactly the same packages as in "provider network" section
  apt-get -y install neutron-server neutron-plugin-ml2 \
  neutron-plugin-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent \
  neutron-metadata-agent
  # python-neutronclient conntrack

   TMPF="/etc/neutron/neutron.conf"
  susti $TMPF database "connection = mysql+pymysql://neutron:${NEUTRON_DB_PASSWORD}@controller/neutron"

  susti $TMPF DEFAULT "core_plugin = ml2"
  susti $TMPF DEFAULT "service_plugins = router"
  susti $TMPF DEFAULT "allow_overlapping_ips = True"

  susti $TMPF DEFAULT "rpc_backend = rabbit"
  susti $TMPF oslo_messaging_rabbit "rabbit_host = controller"
  susti $TMPF oslo_messaging_rabbit "rabbit_userid = openstack"
  susti $TMPF oslo_messaging_rabbit "rabbit_password = ${RABBIT_PASS}"

  susti $TMPF DEFAULT "auth_strategy = keystone"
  susti $TMPF keystone_authtoken "auth_uri = http://controller:5000"
  susti $TMPF keystone_authtoken "auth_url = http://controller:35357"
  susti $TMPF keystone_authtoken "memcached_servers = controller:11211"
  susti $TMPF keystone_authtoken "auth_type = password"
  susti $TMPF keystone_authtoken "project_domain_name = default"
  susti $TMPF keystone_authtoken "user_domain_name = default"
  susti $TMPF keystone_authtoken "project_name = service"
  susti $TMPF keystone_authtoken "username = neutron"
  susti $TMPF keystone_authtoken "password = $NEUTRON_PASSWORD"

  susti $TMPF DEFAULT "notify_nova_on_port_status_changes = True"
  susti $TMPF DEFAULT "notify_nova_on_port_data_changes = True"
  #susti $TMPF DEFAULT "nova_url = http://controller:8774/v2"
  susti $TMPF nova "auth_url = http://controller:35357"
  susti $TMPF nova "auth_type = password"
  susti $TMPF nova "project_domain_name = default"
  susti $TMPF nova "user_domain_name = default"
  susti $TMPF nova "region_name = RegionOne"
  susti $TMPF nova "project_name = service"
  susti $TMPF nova "username = nova"
  susti $TMPF nova "password = $NOVA_PASSWORD"
  #susti $TMPF DEFAULT "verbose = True"


  TMPF="/etc/neutron/plugins/ml2/ml2_conf.ini"
  susti $TMPF ml2  "type_drivers = flat,vlan,vxlan"
  susti $TMPF ml2  "tenant_network_types = vxlan"
  susti $TMPF ml2  "mechanism_drivers = linuxbridge,l2population"
  susti $TMPF ml2  "extension_drivers = port_security"
  susti $TMPF ml2_type_flat "flat_networks = provider"
  susti $TMPF ml2_type_vxlan "vni_ranges = 1:1000"
  susti $TMPF securitygroup "enable_ipset = True"


  TMPF="/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
  susti $TMPF linux_bridge "physical_interface_mappings = provider:$IFACE_EXT"
  susti $TMPF vxlan "enable_vxlan = True"

  MY_MGM_IP=$(ip addr show "$IFACE0" | grep inet | head -n 1 | awk '{print $2}' | cut -d/ -f1 | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

  susti $TMPF vxlan "local_ip = $MY_MGM_IP"
  susti $TMPF vxlan "l2_population = True"
  #susti $TMPF agent "prevent_arp_spoofing = True" 
  susti $TMPF securitygroup "enable_security_group = True"
  susti $TMPF securitygroup "firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver"

  TMPF="/etc/neutron/l3_agent.ini" 
  susti $TMPF DEFAULT "interface_driver = neutron.agent.linux.interface.BridgeInterfaceDriver"
  susti $TMPF DEFAULT "external_network_bridge = "
  #susti $TMPF DEFAULT "verbose = True"

 
  TMPF="/etc/neutron/dhcp_agent.ini"
  susti $TMPF DEFAULT "interface_driver = neutron.agent.linux.interface.BridgeInterfaceDriver"
  susti $TMPF DEFAULT "dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq"
  susti $TMPF DEFAULT "enable_isolated_metadata = True"
  #susti $TMPF DEFAULT "verbose = True"

  # Next line is not in the guide, but it is in training-labs
  #susti $TMPF DEFAULT "dnsmasq_config_file = /etc/neutron/dnsmasq-neutron.conf"
  
  #echo "dhcp-option-force=26,1450" > /etc/neutron/dnsmasq-neutron.conf

}


