#! /bin/bash
##
## This file contains the variables used by BOMSI
## on the openstack environment
##

load_bomsi_functions () {
    for file in /root/bomsi/lib/l_vars /root/bomsi/lib/t_*
        do
            #echo "#### Sourcing $file"
            source $file 
        done
}

## Network type: PROVIDER or SELF_SERVICE
export NET_OPT="SELF_SERVICE"
## Root password for the system
export ROOT_PASSWORD=1234
export NEW_ROOT_PASSWORD=1234
## Network Interfaces (VLANS like eth0.1 or eth0:2 also supported)
export IFACE0=eth0
export IFACE_EXT=eth1
## IP prefixes for Admin, external, Tunnel and Storage networks
export IPPR_A=10.1.0.
export IPPR_EXT=203.1.113.
export NETMASK="255.255.255.0"
export GATEWAY_LN=1
export GATEWAY=${IPPR_A}${GATEWAY_LN}
export DNS_LN=1
export NAMESERVER=${IPPR_A}${DNS_LN}
## Last Digits of IPs of servers
export IPLD_controller=11
export IPLD_compute1=31
export IPLD_compute2=32
export IPLD_compute3=33
export IPLD_neutron=21
## IPs of the servers
export IP_controller=${IPPR_A}${IPLD_controller}
export IP_compute1=${IPPR_A}${IPLD_compute1}
export IP_compute2=${IPPR_A}${IPLD_compute2}
export IP_compute3=${IPPR_A}${IPLD_compute3}
export CONTROLLER_IP=${IP_controller}
export IP_neutron=$IPPR_A$NEUTRON_LN
### PASSWORDS
export MYSQL_ROOT="Password"
export ADMIN_PASS=${MYSQL_ROOT}
export DEMO_PASS=${MYSQL_ROOT}
export RABBIT_USER="admin"
export RABBIT_PASS=${MYSQL_ROOT}
export KEYSTONE_DB_PASSWORD=${MYSQL_ROOT}
export KEYSTONE_REGION="RegionOne"
export KEYSTONE_AUTH_TOKEN=${MYSQL_ROOT}
export GLANCE_DB_PASSWORD=${MYSQL_ROOT}
export GLANCE_PASSWORD=${MYSQL_ROOT}
export NOVA_DB_PASSWORD=${MYSQL_ROOT}
export NOVA_PASSWORD=${MYSQL_ROOT}
export NEUTRON_DB_PASSWORD=${MYSQL_ROOT}
export NEUTRON_PASSWORD=${MYSQL_ROOT}
export METADATA_SECRET="METADATA_SECRET"
export CINDER_DB_PASSWORD=${MYSQL_ROOT}
export CINDER_PASSWORD=${MYSQL_ROOT}
export SWIFT_PASSWORD=${MYSQL_ROOT}
export HEAT_PASSWORD=${MYSQL_ROOT}
export HEAT_DB_PASSWORD=${MYSQL_ROOT}
export HEAT_DOMAIN_PASS=${MYSQL_ROOT}
export CEILOMETER_PASSWORD=${MYSQL_ROOT}
export CEILOMETER_DB_PASSWORD=${MYSQL_ROOT}
export TROVE_PASSWORD=${MYSQL_ROOT}
export TROVE_DB_PASSWORD=${MYSQL_ROOT}
