#! /bin/bash

install_heat () {

 . /root/bomsi/lib/bomsi_vars
 . /root/bomsi/lib/create_sql_user 
 . ~/admin-openrc.sh

  create_sql_user heat $HEAT_DB_PASSWORD

  openstack user create --domain default --password $HEAT_PASSWORD --email heat@os.mydomain.com heat
  openstack role add --project service --user heat admin

  openstack service create --name heat \
  --description "Orchestration" orchestration
  openstack service create --name heat-cfn \
  --description "Orchestration"  cloudformation

  openstack endpoint create --region RegionOne \
   orchestration public http://controller:8004/v1/%\(tenant_id\)s
  openstack endpoint create --region RegionOne \
   orchestration internal http://controller:8004/v1/%\(tenant_id\)s
  openstack endpoint create --region RegionOne \
   orchestration admin http://controller:8004/v1/%\(tenant_id\)s

  openstack endpoint create --region RegionOne \
   cloudformation public http://controller:8000/v1
  openstack endpoint create --region RegionOne \
   cloudformation internal http://controller:8000/v1
  openstack endpoint create --region RegionOne \
   cloudformation admin http://controller:8000/v1

  openstack domain create --description "Stack projects and users" heat
  openstack user create --domain heat --password $HEAT_PASSWORD heat_domain_admin
  openstack role add --domain heat --user heat_domain_admin admin

  openstack role create heat_stack_owner

  openstack role add --project demo --user demo heat_stack_owner

  openstack role create heat_stack_user


  apt-get -y install heat-api heat-api-cfn heat-engine python-heatclient



  TMPF="/etc/heat/heat.conf"
  susti $TMPF database "connection = mysql+pymysql://heat:$HEAT_DB_PASSWORD@controller/heat"

  susti $TMPF DEFAULT "rpc_backend = rabbit"
  susti $TMPF oslo_messaging_rabbit "rabbit_host = controller"
  susti $TMPF oslo_messaging_rabbit "rabbit_userid = openstack"
  susti $TMPF oslo_messaging_rabbit "rabbit_password = ${RABBIT_PASS}"
  susti $TMPF keystone_authtoken "auth_uri = http://controller:5000"
  susti $TMPF keystone_authtoken "auth_url = http://controller:35357"
  susti $TMPF keystone_authtoken "auth_plugin = password"
  susti $TMPF keystone_authtoken "project_domain_id = default"
  susti $TMPF keystone_authtoken "project_name = service"
  susti $TMPF keystone_authtoken "admin_user = heat"
  susti $TMPF keystone_authtoken "admin_password = $HEAT_PASSWORD"

  susti $TMPF trustee "auth_plugin = password"
  susti $TMPF trustee "auth_url = http://controller:35357"
  susti $TMPF trustee "username = heat"
  susti $TMPF trustee "password = $HEAT_PASSWORD"
  susti $TMPF trustee "user_domain_id = default"
  susti $TMPF clients_keystone "auth_uri = http://controller:5000"
  susti $TMPF ec2authtoken "auth_uri = http://controller:5000"
  susti $TMPF DEFAULT "heat_metadata_server_url = http://controller:8000"
  susti $TMPF DEFAULT "heat_waitcondition_server_url = http://controller:8000/v1/waitcondition"
  susti $TMPF DEFAULT "stack_domain_admin = heat_domain_admin"
  susti $TMPF DEFAULT "stack_domain_admin_password = $HEAT_DOMAIN_PASS"
  susti $TMPF DEFAULT "stack_user_domain_name = heat"
  susti $TMPF DEFAULT "verbose = True"


# BULK_VARS=$( heat-keystone-setup-domain \
#  --stack-user-domain-name heat_user_domain \
#  --stack-domain-admin heat_domain_admin \
#  --stack-domain-admin-password $HEAT_DOMAIN_PASS)
#
# STACK_USER_DOMAIN_ID=$(echo "$BULK_VARS" |grep stack_user_domain_id |awk -F= '{print $2}')
# STACK_DOMAIN_ADMIN=$(echo "$BULK_VARS" |grep "stack_domain_admin=" |awk -F= '{print $2}')
# STACK_DOMAIN_ADMIN_PASSWORD=$(echo "$BULK_VARS" |grep "stack_domain_admin_password" |awk -F= '{print $2}')
#
#  susti $TMPF DEFAULT "stack_user_domain_id = $STACK_USER_DOMAIN_ID"


  su -s /bin/sh -c "heat-manage db_sync" heat

  service heat-api restart
  service heat-api-cfn restart
  service heat-engine restart

  rm -f /var/lib/heat/heat.sqlite

  heat service-list
}


