#! /bin/bash

install_nova_node (){

 . /root/bomsi/lib/bomsi_vars

  # Install Packages
  apt-get -y install nova-compute sysfsutils


  TMPF="/etc/nova/nova.conf"

  #rabbit_parameters $TMPF
  susti $TMPF DEFAULT "rpc_backend = rabbit"
  susti $TMPF oslo_messaging_rabbit "rabbit_host = controller"
  susti $TMPF oslo_messaging_rabbit "rabbit_userid = openstack"
  susti $TMPF oslo_messaging_rabbit "rabbit_password = ${RABBIT_PASS}"

  susti $TMPF DEFAULT "auth_strategy = keystone"
  susti $TMPF keystone_authtoken "auth_uri = http://controller:5000"
  susti $TMPF keystone_authtoken "auth_url = http://controller:35357"
  susti $TMPF keystone_authtoken "auth_plugin = password"
  susti $TMPF keystone_authtoken "project_domain_id = default"
  susti $TMPF keystone_authtoken "user_domain_id = default"
  susti $TMPF keystone_authtoken "project_name = service"
  susti $TMPF keystone_authtoken "username = nova"
  susti $TMPF keystone_authtoken "password = $NOVA_PASSWORD"

  MY_MGM_IP=$(ip addr show "$IFACE0" | grep inet | head -n 1 | awk '{print $2}' | cut -d/ -f1 | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

  susti $TMPF DEFAULT "my_ip = $MY_MGM_IP"

  susti $TMPF DEFAULT "network_api_class = nova.network.neutronv2.api.API"
  susti $TMPF DEFAULT "security_group_api = neutron"
  susti $TMPF DEFAULT "linuxnet_interface_driver = nova.network.linux_net.NeutronLinuxBridgeInterfaceDriver"
  susti $TMPF DEFAULT "firewall_driver = nova.virt.firewall.NoopFirewallDriver" 

  susti $TMPF vnc "enabled = True"
  susti $TMPF vnc "vncserver_listen = 0.0.0.0"
  susti $TMPF vnc "vncserver_proxyclient_address = \$my_ip"
  #susti $TMPF vnc "novncproxy_base_url = http://controller:6080/vnc_auto.html"
  susti $TMPF vnc "novncproxy_base_url = http://$CONTROLLER_IP:6080/vnc_auto.html"

  susti $TMPF glance "host = controller"
  susti $TMPF oslo_concurrency "lock_path = /var/lib/nova/tmp"
  susti $TMPF DEFAULT "verbose = True"


  TMPF="/etc/nova/nova-compute.conf"
  VCPUS=$(egrep -c '(vmx|svm)' /proc/cpuinfo)
  [ "$VCPUS" == "0" ] && susti $TMPF libvirt "virt_type = qemu"

  # Remove the SQLite database
  rm -f /var/lib/nova/nova.sqlite

  # Restart the compute service
    which nmap || apt-get -y install nmap 
  while ! nmap -p 8774 controller |grep open; do sleep 2 && echo 'waiting for nova in controller' ; done
  service nova-compute restart

}


