#! /bin/bash

install_nova_node_neutron_self-serv () {

 . /root/bomsi/lib/bomsi_vars

  TMPF="/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
  susti $TMPF linux_bridge "physical_interface_mappings = public:$IFACE1" #IFACE_EXT
  susti $TMPF vxlan "enable_vxlan = False"
  susti $TMPF agent "prevent_arp_spoofing = True"
  MY_MGM_IP=$(ip addr show "$IFACE0" | grep inet | head -n 1 | awk '{print $2}' | cut -d/ -f1 | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

  susti $TMPF vxlan "local_ip = $MY_MGM_IP" ## This is different
  susti $TMPF vxlan "el2_population = True"  ## This is different

  susti $TMPF securitygroup "enable_security_group = True" 
  susti $TMPF securitygroup "firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" 
}


