#! /bin/bash

install_neutron_controller_provider () {
 . /root/bomsi/lib/bomsi_vars
 . ~/admin-openrc.sh

  apt-get -y install neutron-server neutron-plugin-ml2 \
  neutron-plugin-linuxbridge-agent neutron-dhcp-agent \
  neutron-metadata-agent python-neutronclient conntrack

  
  TMPF="/etc/neutron/neutron.conf"
  susti $TMPF database "connection = mysql+pymysql://neutron:${NEUTRON_DB_PASSWORD}@controller/neutron"

  susti $TMPF DEFAULT "core_plugin = ml2"
  susti $TMPF DEFAULT "service_plugins = "
  susti $TMPF DEFAULT "allow_overlapping_ips = True"

  susti $TMPF DEFAULT "rpc_backend = rabbit"
  susti $TMPF oslo_messaging_rabbit "rabbit_host = controller"
  susti $TMPF oslo_messaging_rabbit "rabbit_userid = openstack"
  susti $TMPF oslo_messaging_rabbit "rabbit_password = ${RABBIT_PASS}"

  susti $TMPF DEFAULT "auth_strategy = keystone"
  susti $TMPF keystone_authtoken "auth_uri = http://controller:5000"
  susti $TMPF keystone_authtoken "auth_url = http://controller:35357"
  susti $TMPF keystone_authtoken "auth_plugin = password"
  susti $TMPF keystone_authtoken "project_domain_id = default"
  susti $TMPF keystone_authtoken "user_domain_id = default"
  susti $TMPF keystone_authtoken "project_name = service"
  susti $TMPF keystone_authtoken "username = neutron"
  susti $TMPF keystone_authtoken "password = $NEUTRON_PASSWORD"

  susti $TMPF DEFAULT "notify_nova_on_port_status_changes = True"
  susti $TMPF DEFAULT "notify_nova_on_port_data_changes = True"
  susti $TMPF DEFAULT "nova_url = http://controller:8774/v2"
  susti $TMPF nova "auth_url = http://controller:35357"
  susti $TMPF nova "auth_plugin = password"
  susti $TMPF nova "project_domain_id = default"
  susti $TMPF nova "user_domain_id = default"
  susti $TMPF nova "region_name = RegionOne"
  susti $TMPF nova "project_name = service"
  susti $TMPF nova "username = nova"
  susti $TMPF nova "password = $NOVA_PASSWORD"
  susti $TMPF DEFAULT "verbose = True"


  TMPF="/etc/neutron/plugins/ml2/ml2_conf.ini"
  susti $TMPF ml2  "type_drivers = flat,vlan"
  susti $TMPF ml2  "tenant_network_types = "
  susti $TMPF ml2  "mechanism_drivers = linuxbridge"

  #susti $TMPF ml2  "extension_drivers = port_security"
  #susti $TMPF ml2_type_flat  "flat_networks = public"
  #susti $TMPF ml2_type_vxlan  "vni_ranges = 1:1000"
  #susti $TMPF securitygroup "enable_ipset = True"

  TMPF="/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
  susti $TMPF linux_bridge "physical_interface_mappings = public:$IFACE1" #IFACE_EXT
  susti $TMPF vxlan "enable_vxlan = False"
  #susti $TMPF vxlan "local_ip = OVERLAY_INTERFACE_IP_ADDRESS"
  #susti $TMPF vxlan "el2_population = True"
  susti $TMPF agent "prevent_arp_spoofing = True" 
  susti $TMPF securitygroup "enable_security_group = True"
  susti $TMPF securitygroup "firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver"
 
  TMPF="/etc/neutron/dhcp_agent.ini"
  susti $TMPF DEFAULT "interface_driver = neutron.agent.linux.interface.BridgeInterfaceDriver"
  susti $TMPF DEFAULT "dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq"
  susti $TMPF DEFAULT "enable_isolated_metadata = True"
  susti $TMPF DEFAULT "verbose = True"
  #susti $TMPF DEFAULT "dnsmasq_config_file = /etc/neutron/dnsmasq-neutron.conf"
  

}

