#! /bin/bash

install_horizon () {

  #. /root/bomsi/lib/t_vars

  apt-get -y install openstack-dashboard

  TMPF="/etc/openstack-dashboard/local_settings.py"
  sed -i "s/.*OPENSTACK_HOST =.*/OPENSTACK_HOST = \"controller\"/" $TMPF
  sed -i "s/^ALLOWED_HOSTS =.*/ALLOWED_HOSTS = ['*', ]/" $TMPF

  echo "SESSION_ENGINE = 'django.contrib.sessions.backends.cache'" >> $TMPF
  sed -i "s/'LOCATION': '127.0.0.1:11211'/'LOCATION': 'controller:11211'/" $TMPF

  sed -i 's/^OPENSTACK_KEYSTONE_URL =.*/OPENSTACK_KEYSTONE_URL = "http:\/\/\%s:5000\/v3" \% OPENSTACK_HOST/' $TMPF

  sed -i 's/.*OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = .*/OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True/' $TMPF

  echo 'OPENSTACK_API_VERSIONS = {' >> $TMPF
  echo '  "identity": 3,' >> $TMPF
  echo '  "image": 2,' >> $TMPF
  echo '  "volume": 2,' >> $TMPF
  echo '}' >> $TMPF

  sed -i 's/^#OPENSTACK_KEYSTONE_DEFAULT_DOMAIN.*/OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = "default"/' $TMPF

  sed -i 's/.*OPENSTACK_KEYSTONE_DEFAULT_ROLE.*/OPENSTACK_KEYSTONE_DEFAULT_ROLE = "user"/' $TMPF

  echo "OPENSTACK_NEUTRON_NETWORK = {" >> $TMPF
  echo "   'enable_router': False," >> $TMPF
  echo "   'enable_quotas': False," >> $TMPF
  echo "   'enable_ipv6': False," >> $TMPF
  echo "   'enable_distributed_router': False," >> $TMPF
  echo "   'enable_ha_router': False," >> $TMPF
  echo "   'enable_lb': False," >> $TMPF
  echo "   'enable_firewall': False," >> $TMPF
  echo "   'enable_vpn': False," >> $TMPF
  echo "   'enable_fip_topology_check': False," >> $TMPF
  echo "}" >> $TMPF


  ## This things are not in the install guide but I personally like them
  ## Enable password retrieve
  sed -i 's/.*OPENSTACK_ENABLE_PASSWORD_RETRIEVE.*/OPENSTACK_ENABLE_PASSWORD_RETRIEVE = True/'  $TMPF

  ## Use the default OpenStack theme instead of the Ubuntu one
  sed -i '/AVAILABLE_THEMES =/,+4 s/^#//' $TMPF 

  ## Keep the horizon session open for 24 hours
  echo 'SESSION_TIMEOUT = 86400' >> $TMPF

  ## Also change the keystone token expiration time
  sed -i 's/#expiration = .*/expiration = 86400/'  /etc/keystone/keystone.conf
  


  ## Hacks copied from Roger's ocata patch in training-labs
  chown www-data:www-data /var/lib/openstack-dashboard
  chown www-data:www-data /var/lib/openstack-dashboard/secret_key
  chmod 700 /var/lib/openstack-dashboard
  chmod 600 /var/lib/openstack-dashboard/secret_key


  #sed -i 's/.*TIME_ZONE.*/TIME_ZONE = "UTC"/' $TMPF


  
  # Restart apache
  service apache2 reload

}


