#! /bin/bash

install_glance (){

  . /root/bomsi/lib/t_vars
  #. /root/bomsi/lib/create_sql_user
  load_bomsi_functions
 
  log_step ".  > Installing and configuring glance"

  . ~/admin-openrc.sh


  log_step ".  > Creating MySQL user glance"
  ## Create the MySQL/MariaDB user for glance
  #create_sql_user glance $GLANCE_DB_PASSWORD
  sql_user_db glance glance $GLANCE_DB_PASSWORD

  ## Create the keystone user, role and endpoint for glance

  log_step ".  > Creating keystone user glance"
  openstack user create --domain default --password $GLANCE_PASSWORD --email glance@os.mydomain.com glance
  
  log_step ".  > Giving user glance the admin role "
  openstack role add --project service --user glance admin

  log_step ".  > Creating the glance service"
  openstack service create --name glance \
  --description "OpenStack Image" image

  log_step ".  > Creating the glance service endpoints"
  openstack endpoint create --region RegionOne \
    image public http://controller:9292
  openstack endpoint create --region RegionOne \
    image internal http://controller:9292
  openstack endpoint create --region RegionOne \
    image admin http://controller:9292


  ## Install the packages for glance
  apt-get -y install glance 

  TMPF="/etc/glance/glance-api.conf"
     susti $TMPF glance_store "stores = file,http"
     susti $TMPF glance_store "default_store = file"
     susti $TMPF glance_store "filesystem_store_datadir = /var/lib/glance/images/"


  for TMPF in /etc/glance/glance-api.conf /etc/glance/glance-registry.conf
   do
     susti $TMPF database   "connection = mysql+pymysql://glance:${GLANCE_DB_PASSWORD}@controller/glance"
     susti $TMPF keystone_authtoken "auth_uri = http://controller:5000"
     susti $TMPF keystone_authtoken "auth_url = http://controller:35357"
     susti $TMPF keystone_authtoken "auth_type = password"
     susti $TMPF keystone_authtoken "project_domain_name = default"
     susti $TMPF keystone_authtoken "user_domain_name = default"
     susti $TMPF keystone_authtoken "project_name = service"
     susti $TMPF keystone_authtoken "username = glance"
     susti $TMPF keystone_authtoken "password = $GLANCE_PASSWORD"
     susti $TMPF keystone_authtoken "memcached_servers = controller:11211"
     susti $TMPF paste_deploy "flavor = keystone"
    
   done

  su -s /bin/sh -c "glance-manage db_sync" glance

  # Finalizes instalation
  service glance-registry restart
  service glance-api restart

  # Test glance
  log_step ".  > Adding cirros image to glance"

  ## if file is available localy just copy it instead of download
  if [ ! -f /root/LocalRepo/Packages/keystone.py ]; then
#     log_step "cirros copied, not downloaded" 
#     cp /root/bomsi/LocalRepo/cirros-0.3.4-x86_64-disk.img /tmp/images/ 
#  else
#     #yum -y install wget
#    #wget http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
     . /root/bomsi/lib/l_vars
     CIRROS_VERSION=$(echo $CIRROS_IMG | awk -F"-" '{print $2}')
     curl -s -o /root/bomsi/LocalRepo/$CIRROS_IMG http://download.cirros-cloud.net/${CIRROS_VERSION}/${CIRROS_IMG}
  fi

  source ~/admin-openrc.sh

  sleep 2

  glance image-create --name "cirros" \
  --file /root/bomsi/LocalRepo/${CIRROS_IMG} \
  --disk-format qcow2 --container-format bare \
  --visibility public --progress  

  #--file /root/bomsi/LocalRepo/cirros-0.3.4-x86_64-disk.img \

  #glance image-list
  openstack image list



  ## Optionally get an ubuntu image

  ##
  ##  DO NOT load the images below when using the KVM machines
  ##  There is not enough space on the disk!!
  ##  Use ONLY when installed on bigger/baremetal servers
  ##

  glance_ubuntu_img () {
    curl -s -o /root/bomsi/LocalRepo/ubuntu-yakkety-amd64.img http://cloud-images.ubuntu.com/daily/server/yakkety/current/yakkety-server-cloudimg-amd64.img

    glance image-create --name "ubuntu" \
    --file /root/bomsi/LocalRepo/ubuntu-yakkety-amd64.img \
    --disk-format qcow2 --container-format bare \
    --visibility public --progress

     if [ "$(openstack flavor list |wc -l)" -lt "7" ]; then
       openstack flavor create --id 1 --vcpus 1 --ram 256 --disk 3 m1.mini
     fi

  }
  # glance_ubuntu_img

  glance_centos_img () {
    curl -s -o /root/bomsi/LocalRepo/centos-7-amd64.qcow2 http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2

    glance image-create --name "centos7" \
    --file /root/bomsi/LocalRepo/centos-7-amd64.qcow2 \
    --disk-format qcow2 --container-format bare \
    --visibility public --progress

     if [ "$(openstack flavor list |wc -l)" -lt "7" ]; then
       openstack flavor create --id 2 --vcpus 1 --ram 512 --disk 10 m1.medium
     fi
  }

  # glance_centos_img

}


